name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
          
      - name: ApiKey tests
        run: go test ./internal/auth/ -cover
        
      - name: Gosec test
        run: gosec .

  
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check style root
        run: test -z $(go fmt .)
      
      - name: Check style auth
        run : test -z $(go fmt ./internal/auth)
      
      - name: Statick check root
        run : staticcheck .